import 'package:eddyscout_core/eddyscout_core.dart';

/// All curated launches (PDX metro, Oregon City, Scappoose, lower Columbia,
/// WA side).
///
/// [LaunchPoint.latitude]/[LaunchPoint.longitude] are **access** coords (map
/// pin). Optional [LaunchPoint.waterEntryLatitude] /
/// [LaunchPoint.waterEntryLongitude] snap hydro routing to the river channel.
const List<LaunchPoint> kLaunchPoints = [
  LaunchPoint(
    id: 'cathedral_park',
    name: 'Cathedral Park Boat Ramp',
    latitude: 45.588002,
    longitude: -122.758764,
    shortNote:
        'Willamette put-in below St. Johns Bridge; '
        'motorboat traffic and current.',
    riverSystem: RiverSystem.willamette,
    windExposure: WindExposure.moderate,
    tideRelevance: TideRelevance.minor,
    noaaTideStationId: '9439221',
    usgsSiteId: '14211720',
    flowBands: kFlowBandsUsgs14211720WillamettePortland,
  ),
  LaunchPoint(
    id: 'sellwood_riverfront',
    name: 'Sellwood Riverfront Park',
    latitude: 45.466767,
    longitude: -122.663518,
    shortNote:
        'Popular flatwater beach and ramp just north of Sellwood Bridge.',
    riverSystem: RiverSystem.willamette,
    windExposure: WindExposure.moderate,
    tideRelevance: TideRelevance.minor,
    noaaTideStationId: '9439221',
    usgsSiteId: '14211720',
    flowBands: kFlowBandsUsgs14211720WillamettePortland,
  ),
  LaunchPoint(
    id: 'willamette_park_sw',
    name: 'Willamette Park (SW)',
    latitude: 45.477566,
    longitude: -122.670711,
    shortNote: 'Fee ramp seasonally; SW Macadam corridor on the Willamette.',
    riverSystem: RiverSystem.willamette,
    windExposure: WindExposure.moderate,
    tideRelevance: TideRelevance.minor,
    noaaTideStationId: '9439221',
    usgsSiteId: '14211720',
    flowBands: kFlowBandsUsgs14211720WillamettePortland,
  ),
  LaunchPoint(
    id: 'tom_mccall_waterfront',
    name: 'Tom McCall Waterfront (Esplanade)',
    latitude: 45.522904,
    longitude: -122.670008,
    shortNote:
        'Urban riverfront access; verify permitted put-ins and river traffic.',
    riverSystem: RiverSystem.willamette,
    windExposure: WindExposure.moderate,
    tideRelevance: TideRelevance.minor,
    noaaTideStationId: '9439221',
    usgsSiteId: '14211720',
    flowBands: kFlowBandsUsgs14211720WillamettePortland,
  ),
  LaunchPoint(
    id: 'kelley_point',
    name: 'Kelley Point Park (Slough launch)',
    latitude: 45.646369,
    longitude: -122.762165,
    shortNote:
        'Slough-side put-in near park entrance; confluence currents and '
        'Columbia tide influence—check park rules.',
    riverSystem: RiverSystem.slough,
    windExposure: WindExposure.exposed,
    tideRelevance: TideRelevance.major,
    noaaTideStationId: '9440083',
    marineZoneId: 'PZZ210',
  ),
  LaunchPoint(
    id: 'sauvie_island_boat_ramp',
    name: 'Sauvie Island Boat Ramp',
    latitude: 45.653674,
    longitude: -122.838703,
    shortNote:
        'Multnomah Channel / Sauvie Island access; wind, tide, and barge '
        'traffic on the Columbia pool.',
    riverSystem: RiverSystem.columbia,
    windExposure: WindExposure.exposed,
    tideRelevance: TideRelevance.major,
    noaaTideStationId: '9440083',
    marineZoneId: 'PZZ210',
    usgsSiteId: '14144700',
    flowBands: kFlowBandsUsgs14144700ColumbiaVancouver,
  ),
  LaunchPoint(
    id: 'smith_lake_canoe_ramp',
    name: 'Smith Lake Canoe Ramp',
    latitude: 45.613322,
    longitude: -122.714018,
    shortNote:
        'Smith & Bybee Lakes canoe ramp; slough paddling separate from '
        'mainstem current.',
    riverSystem: RiverSystem.slough,
    windExposure: WindExposure.sheltered,
    tideRelevance: TideRelevance.major,
    noaaTideStationId: '9440083',
    marineZoneId: 'PZZ210',
  ),
  LaunchPoint(
    id: 'gleason_memorial_boat_ramp',
    name: 'M. James Gleason Memorial Boat Ramp',
    latitude: 45.600970,
    longitude: -122.619451,
    shortNote:
        'Oaks Bottom / Sellwood area ramp on the Willamette; busy on '
        'weekends.',
    riverSystem: RiverSystem.willamette,
    windExposure: WindExposure.moderate,
    tideRelevance: TideRelevance.minor,
    noaaTideStationId: '9439221',
    usgsSiteId: '14211720',
    flowBands: kFlowBandsUsgs14211720WillamettePortland,
  ),
  LaunchPoint(
    id: 'columbia_slough_paddle_launch',
    name: 'Columbia Slough Paddle Launch',
    latitude: 45.579700,
    longitude: -122.615007,
    shortNote:
        'Columbia Slough put-in; flatwater with industrial boat traffic '
        'nearby.',
    riverSystem: RiverSystem.slough,
    windExposure: WindExposure.sheltered,
    tideRelevance: TideRelevance.major,
    noaaTideStationId: '9440083',
    marineZoneId: 'PZZ210',
  ),
  LaunchPoint(
    id: 'swan_island_boat_ramp',
    name: 'Swan Island Boat Ramp',
    latitude: 45.562584,
    longitude: -122.705344,
    shortNote: 'Port ramp into Willamette / lagoon; industrial traffic nearby.',
    riverSystem: RiverSystem.willamette,
    windExposure: WindExposure.moderate,
    tideRelevance: TideRelevance.minor,
    noaaTideStationId: '9439221',
    usgsSiteId: '14211720',
    flowBands: kFlowBandsUsgs14211720WillamettePortland,
  ),
  LaunchPoint(
    id: 'river_place_marina',
    name: 'River Place Marina carry-down',
    latitude: 45.509666,
    longitude: -122.672684,
    shortNote: 'Marina docks; confirm access and fees with marina staff.',
    riverSystem: RiverSystem.willamette,
    windExposure: WindExposure.sheltered,
    tideRelevance: TideRelevance.minor,
    noaaTideStationId: '9439221',
    usgsSiteId: '14211720',
    flowBands: kFlowBandsUsgs14211720WillamettePortland,
  ),
  LaunchPoint(
    id: 'jefferson_st_milwaukie',
    name: 'Milwaukie Bay Park',
    latitude: 45.443089,
    longitude: -122.642994,
    shortNote: 'Milwaukie Bay Park ramp on the Willamette; motorboat wakes.',
    riverSystem: RiverSystem.willamette,
    windExposure: WindExposure.moderate,
    tideRelevance: TideRelevance.minor,
    noaaTideStationId: '9439221',
    usgsSiteId: '14211720',
    flowBands: kFlowBandsUsgs14211720WillamettePortland,
  ),
  LaunchPoint(
    id: 'george_rogers_park',
    name: 'George Rogers Park',
    latitude: 45.411185,
    longitude: -122.660623,
    shortNote: 'Lake Oswego outlet beach / carry-down on the Willamette.',
    riverSystem: RiverSystem.willamette,
    windExposure: WindExposure.moderate,
    tideRelevance: TideRelevance.none,
    usgsSiteId: '14211720',
    flowBands: kFlowBandsUsgs14211720WillamettePortland,
  ),
  LaunchPoint(
    id: 'cedaroak_boat_ramp',
    name: 'Cedaroak Boat Ramp',
    latitude: 45.390976,
    longitude: -122.629427,
    shortNote: 'West Linn ramp on the Willamette; eddy below Willamette Falls.',
    riverSystem: RiverSystem.willamette,
    windExposure: WindExposure.moderate,
    tideRelevance: TideRelevance.none,
    usgsSiteId: '14211720',
    flowBands: kFlowBandsUsgs14211720WillamettePortland,
  ),
  LaunchPoint(
    id: 'bernert_landing',
    name: 'Willamette Park & Bernert Landing Boat Ramp',
    latitude: 45.340081,
    longitude: -122.649930,
    shortNote:
        'West Linn riverfront park ramp; last public ramp above the falls.',
    riverSystem: RiverSystem.willamette,
    windExposure: WindExposure.moderate,
    tideRelevance: TideRelevance.none,
    usgsSiteId: '14211720',
    flowBands: kFlowBandsUsgs14211720WillamettePortland,
  ),
  LaunchPoint(
    id: 'clackamette_park',
    name: 'Clackamette Park',
    latitude: 45.372335,
    longitude: -122.602988,
    shortNote: 'Clackamas near Willamette confluence; ramp and eddy access.',
    riverSystem: RiverSystem.clackamas,
    windExposure: WindExposure.moderate,
    tideRelevance: TideRelevance.minor,
    noaaTideStationId: '9439221',
    usgsSiteId: '14211010',
    flowBands: kFlowBandsUsgs14211010ClackamasNearOc,
  ),
  LaunchPoint(
    id: 'sportcraft_enrg_oc',
    name: 'eNRG Kayaking',
    latitude: 45.364219,
    longitude: -122.602949,
    shortNote:
        'Oregon City kayak launch and outfitter; last easy access above '
        'Willamette Falls.',
    riverSystem: RiverSystem.willamette,
    windExposure: WindExposure.moderate,
    tideRelevance: TideRelevance.minor,
    noaaTideStationId: '9439221',
    usgsSiteId: '14211010',
    flowBands: kFlowBandsUsgs14211010ClackamasNearOc,
  ),
  LaunchPoint(
    id: 'glenn_otto_troutdale',
    name: 'Glenn Otto Park (Sandy River)',
    latitude: 45.538228,
    longitude: -122.378454,
    shortNote:
        'Sandy River put-in at Troutdale; separate from mainstem Columbia.',
    riverSystem: RiverSystem.columbia,
    windExposure: WindExposure.moderate,
    tideRelevance: TideRelevance.none,
    usgsSiteId: '14137000',
    flowBands: kFlowBandsUsgs14137000SandyTroutdale,
  ),
  LaunchPoint(
    id: 'chinook_landing_marine_park',
    name: 'Chinook Landing Marine Park',
    latitude: 45.561120,
    longitude: -122.443013,
    shortNote:
        'Fairview / Troutdale Columbia put-in; confirm ramp fees and hours.',
    riverSystem: RiverSystem.columbia,
    windExposure: WindExposure.moderate,
    tideRelevance: TideRelevance.major,
    noaaTideStationId: '9440083',
    marineZoneId: 'PZZ251',
    usgsSiteId: '14144700',
    flowBands: kFlowBandsUsgs14144700ColumbiaVancouver,
  ),
  LaunchPoint(
    id: 'scappoose_bay_marina',
    name: 'Scappoose Bay Marina',
    latitude: 45.828824,
    longitude: -122.839828,
    shortNote: 'Multnomah Channel / Columbia side basin; wind and tide aware.',
    riverSystem: RiverSystem.columbia,
    windExposure: WindExposure.exposed,
    tideRelevance: TideRelevance.major,
    noaaTideStationId: '9440083',
    marineZoneId: 'PZZ251',
  ),
  LaunchPoint(
    id: 'st_helens_public_marina',
    name: 'St. Helens Public Dock / Marina',
    latitude: 45.867213,
    longitude: -122.798392,
    shortNote: 'Lower Columbia pool; ship wake and current possible.',
    riverSystem: RiverSystem.columbia,
    windExposure: WindExposure.exposed,
    tideRelevance: TideRelevance.major,
    noaaTideStationId: '9440083',
    marineZoneId: 'PZZ251',
    usgsSiteId: '14144700',
    flowBands: kFlowBandsUsgs14144700ColumbiaVancouver,
  ),
  LaunchPoint(
    id: 'vancouver_wintler',
    name: 'Wintler Community Park',
    latitude: 45.611667,
    longitude: -122.605776,
    shortNote: 'Columbia beach access in Vancouver; tide and barge traffic.',
    riverSystem: RiverSystem.columbia,
    windExposure: WindExposure.exposed,
    tideRelevance: TideRelevance.major,
    noaaTideStationId: '9440083',
    marineZoneId: 'PZZ210',
    usgsSiteId: '14144700',
    flowBands: kFlowBandsUsgs14144700ColumbiaVancouver,
  ),
  LaunchPoint(
    id: 'frenchmans_bar',
    name: "Frenchman's Bar (Ridgefield)",
    latitude: 45.684178,
    longitude: -122.762164,
    shortNote: 'Sandy beach on lower Columbia; current and wind exposure.',
    riverSystem: RiverSystem.columbia,
    windExposure: WindExposure.exposed,
    tideRelevance: TideRelevance.major,
    noaaTideStationId: '9440083',
    marineZoneId: 'PZZ251',
    usgsSiteId: '14144700',
    flowBands: kFlowBandsUsgs14144700ColumbiaVancouver,
  ),
  LaunchPoint(
    id: 'port_of_camas',
    name: 'Port of Camas Marina',
    latitude: 45.578770,
    longitude: -122.380485,
    shortNote: 'Columbia River marina in Camas; confirm dock access and fees.',
    riverSystem: RiverSystem.columbia,
    windExposure: WindExposure.moderate,
    tideRelevance: TideRelevance.major,
    noaaTideStationId: '9440083',
    marineZoneId: 'PZZ251',
    usgsSiteId: '14144700',
    flowBands: kFlowBandsUsgs14144700ColumbiaVancouver,
  ),
  LaunchPoint(
    id: 'washougal_waterfront',
    name: 'Washougal Waterfront Park',
    latitude: 45.578087,
    longitude: -122.377814,
    shortNote:
        'Washougal River near Columbia confluence; verify hazards and wood.',
    riverSystem: RiverSystem.columbia,
    windExposure: WindExposure.moderate,
    tideRelevance: TideRelevance.minor,
    noaaTideStationId: '9440083',
  ),
];

/// Returns the curated launch for [id], or null if not in [kLaunchPoints].
LaunchPoint? findLaunchPointById(String id) {
  for (final p in kLaunchPoints) {
    if (p.id == id) return p;
  }
  return null;
}
