targets:
  $default:
    builders:
      go_router_builder:
        generate_for:
          - lib/routing/app_routes.dart
      riverpod_generator|riverpod_generator:
        generate_for:
          - lib/preferences/key_value_store_provider.dart
