name: eddyscout_core
description: Core utilities, types, and abstractions for the EddyScout workspace.
publish_to: 'none'
version: 0.1.0

resolution: workspace

environment:
  sdk: ^3.11.4

dependencies:
  meta: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0
